Repository agorafoundation/agora, pull requests merged in 2022-11, with the labels that each got.

#202 Adds saveTopic
  server/controller/apis/topicController.js
  server/model/assessment.js
  server/model/topic.js
  server/routes/apis/topicRoutes.js
  server/service/topicService.js
Labels: API, Topics

#207 Feature/community new design implementation
  client/agora/public/css/community/community-gallery.css
  client/agora/public/css/gallery/new-topic-goal.css
  client/agora/public/css/gallery/note-gallery.css
  client/agora/views/community/community-gallery.ejs
  client/agora/views/community/community.ejs
  client/agora/views/dashboard/partials/gallery/note-gallery.ejs
  client/agora/views/dashboard/side-menu/side-menu.ejs
Labels: UI / Front end

#209 Updating ids in dashboard
  client/agora/public/css/gallery/note-gallery.css
  client/agora/public/js/dashboard.js
  client/agora/views/dashboard/partials/gallery/grid-template.ejs
  client/agora/views/dashboard/partials/gallery/list-template.ejs
Labels: Topics, Goals, UI / Front end

#206 Update Image Bug Fix
  server/controller/apis/goalController.js
  server/controller/apis/resourceController.js
  server/controller/apis/topicController.js
Labels: API

#214 192 eslint integration
  server/controller/apis/topicController.js
Labels: Infrastructure

#215 Resolved Issue #213 and other minor updates
  client/agora/public/js/topic-view.js
Labels: bug

#216 Feature/dashboard-duplicate-functionality
  client/agora/public/js/dashboard.js
  client/agora/views/dashboard/partials/gallery/grid-template.ejs
  client/agora/views/dashboard/partials/gallery/list-template.ejs
Labels: UI / Front end

#217 Feature/dashboard fetch update
  client/agora/public/js/dashboard.js
  client/agora/views/dashboard/partials/gallery/list-template.ejs
Labels: UI / Front end

#220 Topic/editor enhancements
  client/agora/public/css/topic.css
  client/agora/public/js/topic-view.js
  client/agora/views/dashboard/partials/topic/open-topic.ejs
  client/agora/views/dashboard/partials/topic/topic-view.ejs
  client/agora/views/dashboard/partials/topic/workspace-manager-modal.ejs
Labels: Tags / Categorization, UI / Front end

#224 Updates resources and goals api to follow api.apiId new name convention
  server/controller/apis/goalController.js
  server/controller/apis/resourceController.js
  server/model/goal.js
  server/model/resource.js
  server/routes/apis/goalRoutes.js
  server/routes/apis/resourceRoutes.js
  server/service/goalService.js
  server/service/resourceService.js
Labels: enhancement, API

#236 Updated request & response schemas for Goals, Topics & Resources
  server/agoraApi.yaml
Labels: documentation, API

#226 Removed extra 'version' field on GET requests and implemented dynamic incrementing on save
  server/controller/apis/goalController.js
  server/service/goalService.js
  server/service/topicService.js
Labels: enhancement, API, Goals

#237 Middleware Features: better auth, input validation, and error handling
  package.json
  server/agora.js
  server/agoraApi.yaml
  server/controller/apis/apiErrorController.js
  server/controller/apis/discussionController.js
  server/db/connection.js
  server/model/util/ApiMessage.js
  server/routes/apiAuthRoutes.js
  server/routes/apis/discussionRoutes.js
  server/routes/middleware/Usage.md
  server/routes/middleware/inputValidation.js
Labels: enhancement, Software Archecture Planning / Design, API

#219 Homepage fix (doesn't break dashboard anymore)
  client/agora/public/assets/img/dashboard_preview.png
  client/agora/public/assets/img/logos/agora_new_temp.png
  client/agora/public/assets/img/signout.png
  client/agora/public/assets/img/topic_preview.png
  client/agora/public/css/agora-theme.css
  client/agora/public/css/styles.css
  client/agora/views/index.ejs
  client/agora/views/partials/topmenu.ejs
Labels: bug, UI Design, UI / Front end, Home Page

#243 Print uncaught error to console and fix discussion enabling
  server/agora.js
  server/service/discussionService.js
Labels: bug

#251 Added validation for visibility update on save<Object> functions.
  server/controller/apis/resourceController.js
  server/controller/apis/topicController.js
Labels: API

#239 230 validate delete attempts on not found ids
  server/controller/apis/resourceController.js
  server/controller/apis/topicController.js
  server/controller/apis/workspaceController.js
  server/service/resourceService.js
  server/service/topicService.js
  server/service/workspaceService.js
Labels: API

#246 Adding interface for discussions and some DOM manipulation for it
  client/agora/public/css/gallery/note-gallery.css
  client/agora/public/css/topic.css
  client/agora/public/js/topic.js
  client/agora/views/dashboard/partials/topic/comment-template.ejs
  client/agora/views/dashboard/partials/topic/discussion-modal.ejs
  client/agora/views/dashboard/partials/topic/topic-view.ejs
Labels: UI / Front end

#248 Enable DB connection over SSL
  .env.example
  server/db/connection.js
Labels: enhancement, Database

#252 233 test image for thunderclient
  server/controller/apis/resourceController.js
  server/controller/apis/topicController.js
  server/controller/apis/workspaceController.js
Labels: bug, API

#253 Fixes public visibility queries given private value
  server/service/resourceService.js
  server/service/topicService.js
  server/service/workspaceService.js
Labels: API

#260 Patches PR #253 - changes visibility of getAllVisibleWorkspaces
  server/service/workspaceService.js
Labels: bug, enhancement

#247 Topic enhancements
  client/agora/public/css/topic.css
  client/agora/public/js/dashboard.js
  client/agora/public/js/topic-view.js
  client/agora/views/dashboard/partials/topic/topic-view.ejs
Labels: Topics

#263 Fix for database changes caused by goal and workspace change
  server/controller/apis/discussionController.js
  server/db/createTablesScript-base-example.sql
  server/service/discussionService.js
Labels: bug
