Repository agorafoundation/agora, pull requests merged in 2022-12, with the labels that each got.

#266 Adds sharedEntity model
  server/model/sharedEntity.js
Labels: enhancement

#271 Discussion fetches
  client/agora/public/js/topic-view.js
  client/agora/public/js/topic.js
  client/agora/views/dashboard/partials/topic/discussion-modal.ejs
  server/model/comment.js
  server/service/discussionService.js
Labels: Discussions

#276 getAllTopicsForWorkspaceId
  client/agora/views/dashboard/partials/topic/topic-view.ejs
  client/agora/views/partials/head.ejs
  server/agoraApi.yaml
  server/controller/apis/workspaceController.js
  server/routes/apis/workspaceRoutes.js
  server/routes/workspaceRoute-Controller-TODO.js
  server/service/workspaceService.js
Labels: API

#268 Added Shared Entity tables to DB creation file
  server/db/createTablesScript-base-example.sql
Labels: Database

#275 workspace.version -> workspace.workspaceVersion
  server/model/workspace.js
Labels: API, Goals

#286 Added sharedEntity router/controller/service
  .vscode/settings.json
  server/controller/apis/sharedEntityController.js
  server/db/createTablesScript-base-example.sql
  server/model/sharedEntity.js
  server/routes/apiAuthRoutes.js
  server/routes/apis/sharedEntityRoutes.js
  server/service/sharedEntityService.js
Labels: API

#292 The Richie Theme Overhaul
  client/agora/public/assets/img/dashboard_preview.png
  client/agora/public/assets/img/topic_preview.png
  client/agora/public/css/agora-theme.css
  client/agora/public/css/dashboard/side-menu.css
  client/agora/public/css/gallery/note-gallery.css
  client/agora/public/css/styles.css
  client/agora/public/css/topic.css
  client/agora/public/js/topic-view.js
  client/agora/views/community/community-gallery.ejs
  client/agora/views/dashboard/dashboard.ejs
  client/agora/views/dashboard/partials/gallery/list-toggle.ejs
  client/agora/views/dashboard/partials/gallery/note-gallery.ejs
  client/agora/views/dashboard/partials/gallery/view-toggle.ejs
  client/agora/views/dashboard/partials/resources.ejs
  client/agora/views/dashboard/partials/topic/topic-view.ejs
  client/agora/views/dashboard/partials/workspaces.ejs
  client/agora/views/dashboard/side-menu/side-menu.ejs
  client/agora/views/partials/topmenu.ejs
Labels: bug, enhancement, UI Design, Topics, Goals, UI / Front end, overhaul

#284 Service Layer Visibility Changes
  server/controller/apis/resourceController.js
  server/controller/apis/topicController.js
  server/controller/apis/workspaceController.js
  server/service/resourceService.js
  server/service/topicService.js
  server/service/workspaceService.js
Labels: API

#285 Force getById API calls to validate visibility
  server/controller/apis/topicController.js
  server/controller/apis/workspaceController.js
  server/service/topicService.js
  server/service/workspaceService.js
Labels: API

#293 Basic copy sharing implemented.
  server/controller/apis/sharedEntityController.js
  server/routes/apis/sharedEntityRoutes.js
Labels: Sharing, API

#308 300 final presentaiton clean up and testing
  .env.example
  server/db/createTablesScript-base-example.sql
Labels: Infrastructure, Review, Launch

#314 309 old logo on signout signin forgotpass pages
  .vscode/settings.json
  README.md
  client/agora/public/assets/img/logos/agora-title.png
  client/agora/public/assets/img/logos/agora.png
  client/agora/public/css/dashboard/side-menu.css
  client/agora/public/js/dashboard.js
  client/agora/public/js/scripts.js
  client/agora/public/js/topic-view.js
  client/agora/public/js/topic.js
  client/agora/views/about.ejs
  client/agora/views/community/community.ejs
  client/agora/views/dashboard/dashboard.ejs
  client/agora/views/dashboard/partials/gallery/note-gallery.ejs
  client/agora/views/dashboard/side-menu/side-menu.ejs
  client/agora/views/partials/head.ejs
  client/agora/views/partials/nomenu.ejs
  client/agora/views/partials/topmenu.ejs
  client/agora/views/user-signup.ejs
  server/controller/apis/apiErrorController.js
  server/model/assessment.js
Labels: UI / Front end, Review, Launch

#319 responsive issues fixed
  client/agora/views/about.ejs
  client/agora/views/dashboard/dashboard.ejs
  client/agora/views/dashboard/partials/gallery/note-gallery.ejs
  client/agora/views/index.ejs
  client/agora/views/partials/topmenu.ejs
  client/agora/views/partials/welcome.ejs
Labels: UI Design, UI / Front end, Review, Launch

#322 sharing link removed from topic / edit screen. only place it was found
  client/agora/views/dashboard/partials/topic/topic-view.ejs
Labels: Sharing, Review, Launch

#324 all parts of interests are removed, this requires a db change
  client/agora/public/js/user.js
  client/agora/views/profile/manage.ejs
  client/agora/views/profile/user.ejs
  client/agora/views/user-manage.ejs
  client/agora/views/user-signup.ejs
  client/codingcoach/public/js/user.js
  client/codingcoach/views/auth/dashboard.ejs
  client/codingcoach/views/community/user.ejs
  client/codingcoach/views/user-manage.ejs
  client/codingcoach/views/user-signup.ejs
  server/controller/userController.js
  server/db/createTablesScript-base-example.sql
  server/model/user.js
  server/service/userService.js
Labels: Database, Review, Launch

#334 306 tags are not showing up when returning to a saved workspace
  client/agora/public/js/topic-view.js
  server/agoraApi.yaml
  server/controller/apis/tagController.js
  server/controller/apis/workspaceController.js
  server/db/createDatabase.sql
  server/model/tagged.js
  server/routes/apis/tagRoutes.js
  server/service/tagService.js
  server/service/workspaceService.js
Labels: Tags / Categorization, API, Review, Launch

#335 found issue with id's and resources preventing multiple editors
  client/agora/public/js/topic-view.js
Labels: bug, UI / Front end, Review, Launch

#336 333 after logging in users should be dropped into the dashboard not their profile
  LICENSE
  client/agora/public/css/agora-theme.css
  client/agora/public/css/dashboard/side-menu.css
  client/agora/public/css/gallery/note-gallery.css
  client/agora/public/css/styles.css
  client/agora/public/js/dashboard.js
  client/agora/public/js/scripts.js
  client/agora/public/js/topic-view.js
  client/agora/views/about.ejs
  client/agora/views/codebot.ejs
  client/agora/views/community/join.ejs
  client/agora/views/community/template.ejs
  client/agora/views/community/topic.ejs
  client/agora/views/community/workspace.ejs
  client/agora/views/dashboard/partials/gallery/control-bar.ejs
  client/agora/views/dashboard/partials/gallery/list-toggle.ejs
  client/agora/views/dashboard/partials/gallery/note-gallery.ejs
  client/agora/views/dashboard/partials/gallery/view-toggle.ejs
  client/agora/views/dashboard/side-menu/side-menu.ejs
  client/agora/views/index.ejs
  client/agora/views/orginal-template.html
  client/agora/views/partials/copyright.ejs
  client/agora/views/partials/footer.ejs
  client/agora/views/partials/head.ejs
  client/agora/views/partials/jsincludes.ejs
  client/agora/views/partials/message.ejs
  client/agora/views/partials/topmenu.ejs
  client/agora/views/profile/manage.ejs
  client/agora/views/profile/user.ejs
  client/agora/views/purchase/access-token-cancel.ejs
  client/agora/views/purchase/access-token-success.ejs
  client/agora/views/purchase/codebot1-cancel.ejs
  client/agora/views/purchase/codebot1-success.ejs
  client/agora/views/purchase/founders-cancel.ejs
  client/agora/views/purchase/founders-success.ejs
  client/agora/views/sign-in.ejs
  client/agora/views/user-error.ejs
  client/agora/views/user-forgot-password.ejs
  client/agora/views/user-reset-password-sent.ejs
  client/agora/views/user-reset-password.ejs
  client/agora/views/user-signup.ejs
  client/agora/views/user-welcome.ejs
  server/controller/authController.js
  server/routes/authRoutes.js
  server/routes/dashboardRoutes.js
Labels: UI Design, UI / Front end, Review, Launch

#340 removed all head - body - html pieces for #316 also quickfix for publ…
  client/agora/views/community/community-gallery.ejs
  client/agora/views/dashboard/partials/topic/edit-note.ejs
  client/agora/views/profile/user.ejs
  server/routes/pagesRoutes.js
  server/routes/topicRoutes.js
  server/service/userService.js
Labels: UI / Front end
