Repository agorafoundation/agora, pull requests merged in 2022-09, with the labels that each got.

#113 105 create the resource api stack
  client/agora/views/dashboard/partials/resource/edit-resource.ejs
  server/controller/apis/goalController.js
  server/controller/apis/resourceController.js
  server/controller/communityController.js
  server/db/createTablesScript-base-example.sql
  server/routes/apis/goalRoutes.js
  server/routes/apis/resourceRoutes.js
  server/routes/apis/tagRoutes.js
  server/routes/dashboardRoutes.js
  server/service/goalService.js
  server/service/resourceService.js
  server/service/tagService.js
Labels: API

#140 Updated the readme to remove coding coach line
  README.md
Labels: documentation

#141 Refined the readme to reflect current development
  README.md
Labels: documentation, Product Planning

#149 fix imports for user model
  server/controller/apis/userController.js
  server/controller/userController.js
  server/service/goalService.js
  server/service/topicService.js
  server/service/userService.js
Labels: bug

#159 Adds authentication fix for UI.
  client/agora/public/assets/uploads/goal/peak.svg
  server/controller/apis/resourceController.js
  server/routes/apiAuthRoutes.js
Labels: bug

#162 Adds delete resources by id handler
  server/controller/apis/resourceController.js
  server/routes/apis/resourceRoutes.js
  server/service/resourceService.js
Labels: enhancement

#164 Feature/topic
  client/agora/public/css/agora-theme.css
  client/agora/public/css/dashboard/side-menu.css
  client/agora/public/css/note.css
  client/agora/public/css/styles.css
  client/agora/public/js/note.js
  client/agora/views/dashboard/partials/gallery/dropdown.ejs
  client/agora/views/dashboard/partials/topic/edit-note.ejs
  client/agora/views/dashboard/partials/topic/file-display.ejs
  client/agora/views/dashboard/side-menu/side-menu.ejs
  client/agora/views/partials/head.ejs
  client/agora/views/partials/jsincludes.ejs
  server/routes/pagesRoutes.js
Labels: enhancement, UI Design, Topics, UI / Front end

#166 Fixed Dashboard wysiwyg
  client/agora/views/dashboard/partials/gallery/note-gallery.ejs
Labels: bug, UI / Front end
