Repository agorafoundation/agora, pull requests merged in 2022-10, with the labels that each got.

#172 Feature/topic updated layout and tag search
  client/agora/public/css/note.css
  client/agora/public/js/note.js
  client/agora/views/dashboard/partials/topic/edit-note.ejs
  client/agora/views/dashboard/partials/topic/file-display.ejs
Labels: enhancement, Topics, UI / Front end

#171 Feature/dashboard toggle goal topic all
  client/agora/public/css/gallery/note-gallery.css
  client/agora/public/js/dashboard.js
  client/agora/views/dashboard/partials/gallery/note-gallery.ejs
Labels: UI Design, UI / Front end

#176 Fixed getResourceById
  server/controller/apis/resourceController.js
  server/service/resourceService.js
Labels: Resources, API

#179 Dashboard view toggle and "More Options" rename button and modal + DOM manipulation on dashboard cards
  client/agora/public/css/gallery/note-gallery.css
  client/agora/public/js/dashboard.js
  client/agora/views/dashboard/partials/gallery/dropdown.ejs
  client/agora/views/dashboard/partials/gallery/note-gallery.ejs
  client/agora/views/dashboard/partials/gallery/preview-modal.ejs
  client/agora/views/dashboard/partials/gallery/rename-modal.ejs
  client/agora/views/dashboard/partials/gallery/render-card.ejs
  client/agora/views/dashboard/partials/gallery/view-toggle.ejs
Labels: UI Design, UI / Front end

#174 Swagger API Docs
  server/agoraApi.yaml
Labels: documentation, API

#181 Feature/dashboard duplicate
  client/agora/public/js/dashboard.js
  client/agora/views/dashboard/partials/gallery/delete-modal.ejs
  client/agora/views/dashboard/partials/gallery/dropdown.ejs
  client/agora/views/dashboard/partials/gallery/new-topic-goal.ejs
  client/agora/views/dashboard/partials/gallery/note-gallery.ejs
Labels: UI Design, UI / Front end

#180 Bugfix/dashboard more options goal broken
  client/agora/public/css/dashboard/side-menu.css
  client/agora/public/css/gallery/note-gallery.css
  client/agora/public/js/dashboard.js
  client/agora/public/js/note.js
  client/agora/views/dashboard/partials/gallery/note-gallery.ejs
  client/agora/views/dashboard/side-menu/side-menu.ejs
Labels: UI Design, UI / Front end

#163 Goal api (antonio and james)
  server/controller/apis/goalController.js
  server/controller/apis/resourceController.js
  server/routes/apis/goalRoutes.js
  server/service/goalService.js
Labels: API, Goals

#178 Building Topics API Stack and fixed SQL query for getAllVisibleTopics
  server/controller/apis/topicController.js
  server/routes/apiAuthRoutes.js
  server/routes/apis/goalRoutes.js
  server/routes/apis/topicRoutes.js
  server/service/topicService.js
Labels: API, Topics

#187 Resource upload -- Topic Page
  client/agora/public/css/note.css
  client/agora/public/css/styles.css
  client/agora/public/js/dashboard.js
  client/agora/public/js/note.js
  client/agora/views/dashboard/partials/topic/edit-note.ejs
Labels: enhancement, UI / Front end

#191 Feature/side menu burger
  client/agora/public/css/dashboard/side-menu.css
  client/agora/public/css/gallery/note-gallery.css
  client/agora/views/dashboard/partials/gallery/new-topic-goal.ejs
  client/agora/views/dashboard/partials/gallery/note-gallery.ejs
  client/agora/views/dashboard/partials/gallery/view-toggle.ejs
  client/agora/views/dashboard/side-menu/side-menu.ejs
Labels: UI Design, UI / Front end

#200 Feature/dashboard listview2
  client/agora/public/css/gallery/note-gallery.css
  client/agora/public/js/dashboard.js
  client/agora/views/dashboard/partials/gallery/grid-template.ejs
  client/agora/views/dashboard/partials/gallery/list-template.ejs
  client/agora/views/dashboard/partials/gallery/list-toggle.ejs
Labels: UI / Front end

#205 Feature/topic share
  client/agora/public/css/topic.css
  client/agora/public/js/dashboard.js
  client/agora/public/js/topic-view.js
  client/agora/views/dashboard/partials/topic/share-modal.ejs
  client/agora/views/dashboard/partials/topic/topic-view.ejs
Labels: UI / Front end

#189 146 Create Discussion API Stack
  server/agoraApi.yaml
  server/controller/apis/discussionController.js
  server/db/createTablesScript-base-example.sql
  server/model/comment.js
  server/model/discussion.js
  server/routes/apiAuthRoutes.js
  server/routes/apis/discussionRoutes.js
  server/service/discussionService.js
  server/service/goalService.js
Labels: Discussions, API
