Repository agorafoundation/agora, pull requests merged in 2023-12, with the labels that each got.

#495 fixed the ordering of resources and added a default resource
  client/agora/public/css/topic.css
  client/agora/public/js/dashboard.js
  client/agora/public/js/editorMain.js
  client/agora/public/js/editorManager.js
  client/agora/public/js/state/stateManager.js
  server/controller/apis/workspaceController.js
Labels: Resources, UI / Front end

#498 496 resource title visibility
  client/agora/public/css/topic.css
  client/agora/public/js/editorManager.js
  server/controller/authController.js
  server/controller/userController.js
Labels: UI / Front end, SSO

#502 500 master both
  .env.example
  client/agora/public/css/note.css
  client/agora/public/css/topic.css
  client/agora/public/js/agnesAI.js
  client/agora/public/js/controllers/clientTopicController.js
  client/agora/public/js/controllers/clientWorkspaceController.js
  client/agora/public/js/dashboard.js
  client/agora/public/js/editorMain.js
  client/agora/public/js/editorManager.js
  client/agora/public/js/friends.js
  client/agora/public/js/share-topic-view.js
  client/agora/public/js/state/stateManager.js
  client/agora/views/dashboard-shared/partials/gallery/control-bar.ejs
  client/agora/views/dashboard-shared/partials/gallery/dropdown.ejs
  client/agora/views/dashboard-shared/side-menu/side-menu.ejs
  client/agora/views/dashboard/partials/topic/agnes-data-template.ejs
  client/agora/views/dashboard/partials/topic/agnes-modal.ejs
  client/agora/views/dashboard/partials/topic/comment-template.ejs
  client/agora/views/dashboard/partials/topic/discussion-modal.ejs
  client/agora/views/dashboard/partials/topic/topic-view.ejs
  client/agora/views/friends/partials/gallery/dropdown.ejs
  client/agora/views/partials/jsincludes.ejs
  package.json
  server/agoraApi.yaml
  server/controller/apis/aiController.js
  server/controller/apis/friendController.js
  server/controller/apis/sharedEntityController.js
  server/controller/apis/topicController.js
  server/controller/apis/userController.js
  server/controller/apis/workspaceController.js
  server/controller/dashboardController.js
  server/controller/dashboardSharedController.js
  server/controller/profileController.js
  server/model/friendshipRequest.js
  server/routes/apiAuthRoutes.js
  server/routes/apis/aiRoutes.js
  server/routes/apis/friendRoutes.js
  server/routes/apis/sharedEntityRoutes.js
  server/routes/apis/userRoutes.js
  server/routes/apis/workspaceRoutes.js
  server/routes/dashboardRoutes.js
  server/routes/dashboardSharedRoutes.js
  server/routes/sharedDashboardRoutes.js
  server/routes/topicRoutes.js
  server/service/friendService.js
  server/service/resourceService.js
  server/service/sharedEntityService.js
  server/service/userService.js
  server/service/workspaceService.js
Labels: Sharing, Launch, AI

#503 modifications on the friend page
  client/agora/public/js/friends.js
  client/agora/views/dashboard/side-menu/side-menu.ejs
  client/agora/views/friends/partials/gallery/grid-template.ejs
  server/controller/apis/friendController.js
  server/model/friendship.js
  server/model/user.js
  server/service/friendService.js
Labels: Sharing, API, UI / Front end

#488 487 relative modal position
  client/agora/public/css/topic.css
  client/agora/public/js/agnesAI.js
Labels: UI Design, UI / Front end, AI

#479 Security policy & code of conduct
  CODE_OF_CONDUCT.md
  SECURITY.md
Labels: documentation

#504 500 attempt to merge ai branch with main
  client/agora/public/css/topic.css
Labels: AI

#511 510 tags are broken
  client/agora/public/js/controllers/clientTagController.js
  client/agora/public/js/editorMain.js
  client/agora/public/js/editorManager.js
  client/agora/public/js/state/stateManager.js
  client/agora/views/dashboard/partials/topic/topic-view.ejs
  client/agora/views/profile/manage.ejs
  server/controller/apis/tagController.js
  server/controller/apis/userController.js
  server/model/tagged.js
  server/routes/apis/userRoutes.js
  server/routes/topicRoutes.js
  server/service/userService.js
Labels: Tags / Categorization, UI / Front end

#512 509 dashboard search is broken
  client/agora/public/js/dashboard.js
  client/agora/public/js/state/stateManager.js
  client/agora/views/dashboard/partials/gallery/grid-template.ejs
  server/controller/apis/sharedEntityController.js
  server/controller/userController.js
  server/service/userService.js
Labels: bug, UI Design, UI / Front end

#516 514 dalle
  client/agora/public/css/agora-theme.css
  client/agora/public/js/user.js
  client/agora/views/profile/manage.ejs
  package.json
  server/controller/apis/aiController.js
  server/routes/apis/aiRoutes.js
Labels: AI

#518 517 limit the number of free dall e generations
  client/agora/public/js/user.js
  client/agora/views/profile/manage.ejs
  server/controller/userController.js
  server/db/createDatabase.sql
  server/db/v2-db-upgrade.sql
  server/model/user.js
  server/routes/apis/aiRoutes.js
  server/service/userService.js
Labels: API, AI, DALL-E

#520 519 friend requests should generate an email
  server/controller/apis/friendController.js
  server/service/userService.js
Labels: Sharing, Collab

#526 522 test implement gpt 4 for agnes
  .vscode/settings.json
  client/agora/public/js/agnesAI.js
  server/controller/apis/aiController.js
Labels: API, UI / Front end, AI

#527 524 work needs a version or method to ensure that new work is not overwritten by old work
  client/agora/public/js/controllers/clientResourceController.js
  client/agora/public/js/editorManager.js
  client/agora/public/js/state/stateManager.js
  server/controller/apis/resourceController.js
  server/db/createDatabase.sql
  server/db/v2-db-upgrade.sql
  server/model/resource.js
  server/routes/topicRoutes.js
  server/service/resourceService.js
Labels: API, Database, Launch

#529 523 workspaces should display with most recently changed first
  server/db/createDatabase.sql
  server/db/v2-db-upgrade.sql
  server/model/topic.js
  server/model/workspace.js
  server/service/resourceService.js
  server/service/topicService.js
  server/service/workspaceService.js
Labels: enhancement, UI Design, Launch

#531 528 add the bio and avatar generation as part of the user creation process
  client/agora/public/js/controllers/clientWorkspaceController.js
  client/agora/views/user-signup.ejs
  server/controller/userController.js
Labels: UI Design, UI / Front end, AI
